// <auto-generated />
using System;
using Lucky.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lucky.WebAPI.Migrations
{
    [DbContext(typeof(LuckyDbContext))]
    [Migration("20240717120650_changesfordateofbirth")]
    partial class changesfordateofbirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lucky.WebAPI.Data.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90c85973-e041-426b-844f-6da44d8476f7"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("0e71c6fd-029c-45f3-a50f-24ecb665be28"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("34fcb5ea-2c24-42be-8d00-4b0a9b11b112"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("73719923-2273-490a-95b3-bea7e50dda31"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("2b1ee6fe-9aa2-4051-92e7-e4785aa5e1f9"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("6f89594f-e10a-4e03-aaad-7ed1dd0c7223"),
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("e5bf2b2c-8323-468c-8769-a2dd176819ec"),
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = new Guid("6a510ff4-e53d-47dc-ae96-9ad7087bc984"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("3f44d53c-0144-4767-a853-62f9aa9fb2a7"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("69bef911-19c0-446a-b7a9-daddc168e49c"),
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("78de81da-da6c-41be-839e-43f957da3b81"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("a57e6695-8493-463d-b7bf-d0f657d63d8b"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("95f08581-75d6-4805-b952-684ac7e30e97"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("492954c7-9890-424d-bc6e-f8653f7e4b1e"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("e5ae641c-15e4-48aa-97b4-c70ab27300b1"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("38a6a5be-6662-49d4-be7f-70b2a414da6e"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("52278c98-6b5d-40f5-9781-ef566504ac3e"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("6fcad100-325d-488c-82e7-e05fa4d544ac"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("c018bc32-7300-4be1-ad3b-f23eee1b5fb6"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("0a25e936-d7d1-4ad3-a966-46508c3cf12f"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("55046d53-37f1-4506-853d-aa47d78201d9"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("1721a532-e3e0-4378-8f5b-7f43fd07f5ed"),
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = new Guid("f632050a-2e42-4e2e-8369-42f1248d896c"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("a67ea461-8279-42e3-a8c7-0ea7bc255ea8"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("9cc29c9d-3422-4e2b-ab9f-76c3c9bcc6f4"),
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("13fd84ea-aad9-4099-a1f5-c34060521dc4"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("29e2bc4e-ba1e-4dbe-8ff0-fd5514e0ee61"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("d228c0a0-1d0f-4177-a8dc-ff82987db764"),
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = new Guid("0401e7ee-e044-4ed6-b974-6665c65ef343"),
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("cdbda70f-acf8-43e4-abbc-5177c922d295"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("ef6fb37f-a801-4bec-a06c-c919ac3a2bb0"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("82d24351-f965-4283-ab98-2c31094608aa"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("560bfaf5-443e-40ed-be74-178d21a1f2c8"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("52a9a2f0-d20c-4035-8a62-1d62d6b8da28"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("027a5c92-b435-4cef-b101-2ae8d04ba5e0"),
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = new Guid("3ef3fb40-2fc1-4eb4-ac20-165170d6baca"),
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = new Guid("af91610e-ebb7-4d9b-ae07-64359a17ca78"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("ddbd2548-4a6e-4562-a536-66a54f2fc6a2"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("05e534ab-1d64-4780-8e94-bfb64f7876e2"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("1be64f8c-0dca-45a8-ba23-6a22b33c75ca"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("f3c9d37f-5489-4293-aa46-36d55262fd91"),
                            Name = "Congo"
                        },
                        new
                        {
                            Id = new Guid("5909435b-a698-4a1c-8972-db316662070a"),
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = new Guid("71eacb8d-2d10-4dae-b1f5-59fdb07497ee"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("9f5a7c18-10e6-4599-b01f-c7b3acf66e1a"),
                            Name = "Cote D Ivoire"
                        },
                        new
                        {
                            Id = new Guid("5f265fca-c114-43d2-a40c-c05d429bedbd"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("4276486d-14ca-4e91-8360-b7cd8e765398"),
                            Name = "Cruise Ship"
                        },
                        new
                        {
                            Id = new Guid("e6045c06-d9e5-4747-bc26-08d9dfc22c70"),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("8452bf05-486e-49ae-acd7-cb384ec5813b"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("63af4f80-ca2c-4606-bc54-47eda15b5ef1"),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("504c8ad4-11bf-4ff7-a1fa-0276af407220"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("c4420834-65be-4ae7-a2e8-8d0efe559f1d"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("43f9db2a-f117-4b63-9168-6fe34ae1f424"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("fa5d9cc7-ad83-43f6-9a32-0a299690513b"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("89776af9-7684-450a-93ed-e4cb69a13f48"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("05147ebf-348b-488b-ab6f-ce30ae1e3045"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("5e6b5d93-78eb-41d7-906f-bdbaf856feaa"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("04506df7-222d-4e85-8fa1-ac5056f6b9cd"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("d935b6db-80b9-4e9d-8b8c-d675296b1b37"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("0bcbc121-ee89-471b-802a-ed2dca6cb7d9"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("c0508062-ebe7-4148-bb6a-234187220b16"),
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = new Guid("e57ee3b7-b6e6-478d-8ea1-9edd80d605ee"),
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = new Guid("86bb5fa0-2d5a-4e52-84ed-9a22ce8b0a04"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("f813d673-3de1-4524-984b-1f6ac3c41e4b"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("70c33217-fd18-4e29-8287-3823ea475f2e"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("53fa7b94-4a14-4ea0-9d94-6b1dcf452e0b"),
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = new Guid("76cf6cd0-1378-4574-9259-b3b09dabfdbe"),
                            Name = "French West Indies"
                        },
                        new
                        {
                            Id = new Guid("1eba316f-7f21-45eb-9213-901a85b78527"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("098477a3-71d2-47a5-a365-7dd270e4fee7"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("5a9cb042-d334-47bc-a3c2-de9e96130d60"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("602003e7-c62f-4da7-ae53-851f3cf8679b"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("1dd1520b-3429-485c-ab4e-19553afeefda"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("50e018f4-4e1a-4b41-b5e9-9abc03f9c60d"),
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("4586c79f-c82a-415d-be21-5928e6ee1065"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("58044f02-607c-4c53-b34a-94e9deaec186"),
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = new Guid("f4b1225e-1460-404c-b414-735e5679c2e9"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("f285257e-60ba-464c-a3c8-1a7ea058317f"),
                            Name = "Guam"
                        },
                        new
                        {
                            Id = new Guid("e9a231c1-9840-4487-8f26-0f061de6d0fa"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("e599f9cd-21d4-460c-8b16-385a2e596a7c"),
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("f364071a-1576-48c9-a692-0ddb585f14c9"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("9db8b008-1fc3-439d-96b0-05a4c9f4960e"),
                            Name = "Guinea Bissau"
                        },
                        new
                        {
                            Id = new Guid("4b0834b9-93f9-4276-bca8-a6f10ba4b047"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("17ae4ed1-1da3-4716-ba75-f2f3f011cd49"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("4096c2fa-a202-43fd-ba6f-d3b65ff79489"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("7efa4a61-0a65-462d-b7e7-746b2e7debb9"),
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("98827b0d-a3ca-4dd2-a74e-92342612c96a"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("aa7b9373-6337-4896-bbc0-b3427c8b62a2"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("70ccc47c-0f2c-40f5-a8a9-e9dc7615e351"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("876ebbf7-abe9-4d23-bf98-1f8d63fd2742"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("165ddfc2-2b25-4747-b7e9-ae2ea1a19e18"),
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("da4d9421-5390-4505-ab68-4898c95e66e0"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("c2e97b15-4e2d-47bc-bb1f-c8f36aabe91b"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("7b2a3f36-58eb-42a7-9ab5-fed471b1ebc0"),
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = new Guid("c9e77c98-c2e4-4a83-abe7-b63b56dd88f9"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("fa6e10d3-4939-4d85-8cb6-b31f8691cc2f"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("79586d6b-62f3-4378-a2ea-8f4644b48e36"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("4051196a-e8dc-42bc-ae9b-f605cfe62668"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("12377c2c-f428-47a5-be22-75a929559e1a"),
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("274edd87-0a2c-40bd-9e47-13e4fc09b90e"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("fa2b40dc-131f-4eaa-91d5-346fb5c701a8"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("25e2f0c8-8c2a-4690-920a-50ced4b931d4"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("9ecbb104-9e21-40e8-99b5-60bd299d7470"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("23ba6ed0-5b33-4315-9d5c-64724ff807af"),
                            Name = "Kyrgyz Republic"
                        },
                        new
                        {
                            Id = new Guid("bf947807-043a-4e30-824a-0e0342a1bb2b"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("c427bc20-d8b3-4e81-a8a8-c6de66e3814e"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("055024c6-d3ac-468e-9aba-dcb9e3e767b6"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("6aec4217-37a6-49f4-9595-6ed33c477e41"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("4b2792ed-d574-44a8-ad66-84228aad102c"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("56ba438b-33e1-4f2d-8ee6-bd6430fc81fc"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("09536dc3-2a68-4dd8-a564-4db3103b3965"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("f337ec79-c9a3-4f58-8607-331283a380fd"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("1246e20a-694d-4b6d-9fa7-d57769865d46"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("970ca75d-769f-45e4-98b7-f617bb01c126"),
                            Name = "Macau"
                        },
                        new
                        {
                            Id = new Guid("09883b1c-b780-40e7-a479-cef69725b326"),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = new Guid("79a26350-ec78-4f8b-a65c-3d1dd3442010"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("3c67d443-45b6-4cf3-8e89-1179f24832fb"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("24d47c20-fef4-4ad3-9b74-ad410dfa0024"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("c9de01df-4a61-4ae6-89e6-44830f87c746"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("dcfedce1-cb04-40cb-bfee-b5d9bafe05b0"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("474ac0b8-0a54-4461-b502-79e833ff8d0e"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("87a39d3f-4a30-4f29-ab1d-16f80c07c057"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("62ecc835-a2a1-4392-b677-a67bf6da48cc"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("cb76f657-f7d4-4c3e-8666-644ddcd00118"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("cca07c1f-d888-445f-9381-928297ce46bf"),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("1ec8bfe8-6044-4fb7-a633-0ab8d2ecd4fa"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("12a51609-af96-4a3a-9182-90db3ca428b6"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("638d0a0d-58c7-4690-96a4-0dc99696257b"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("4686bc31-3212-42fd-bf1d-e31960f97c75"),
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("879d4c11-cd6d-48e8-ad98-c3def847a34a"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("e4db020b-265b-4dc0-945c-af060fa437a5"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("96b14721-29cc-43de-a3ca-d0c030a24fe2"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("78669028-44d8-4a13-99ea-8bf916bfbd53"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("e7246f0b-90f3-40b0-96ed-be9e381a254e"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("f3a43ae4-e518-4a80-b634-dcdde558f17f"),
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = new Guid("4f153e0a-3067-458d-8287-ae7472d3ca55"),
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = new Guid("9038d2f1-00c8-4eef-8dbd-01ae2e0d22cb"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("a102f62f-bce0-46f1-9f26-a0bfbb7e5460"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("a494225d-8024-451e-91d3-61cf00960a5e"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("3402f2ec-3e33-4206-b783-ef2cf912e796"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("5cbf3d96-c8ec-4f74-be8e-1cb0ce340654"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("26062cc7-b03e-4047-a71f-7d0a51d1f7eb"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("7dc414e8-e1de-44f7-abf9-2bf42bb5ad9e"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("66caf86a-8986-46a0-a49a-de1382f9bb27"),
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = new Guid("4efc7a04-4437-4147-8967-5d58f9c31952"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("3c426743-c29a-4861-96d8-af28c3ac4ec8"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("ceb93949-6abf-4614-b850-4ff20e7ecb94"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("a373bffc-6821-489c-a428-c4fe66693c71"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("7863e620-35e9-432d-8640-d853301c96ac"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("50742f2f-aab6-4b82-a2be-fa9dc570c153"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("8c1aa63d-6bb1-4327-bf5e-a20a4cf8248a"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("ead42595-dff9-43a6-9393-1803fc0a4c8f"),
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = new Guid("761468b9-fcf6-4d93-9c62-0b0e50e300c0"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("1681c9f9-6675-4129-8cbd-d72743ad026b"),
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = new Guid("880cc09f-34d7-40c4-b638-f47ae28f2048"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("4952f3e0-ed5f-40e4-863b-35356834df0b"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("05768efc-ba4c-4d2e-b24b-2c1f7d2e6bdb"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("9712dfb1-403d-4a60-96d4-06f680bc9a7a"),
                            Name = "Saint Pierre & Miquelon"
                        },
                        new
                        {
                            Id = new Guid("5484d8ab-3161-4d54-b75f-e1f12db92dee"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("01838d71-f338-425a-b7e4-49f9f9c67f7c"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("df5bccf0-92fd-407e-bdd9-7bc085db3172"),
                            Name = "Satellite"
                        },
                        new
                        {
                            Id = new Guid("36073d03-4b54-451a-8b7f-1e8e2d38a832"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("2204e9fb-54de-422e-97ac-2e17e55528e8"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("0638f534-0991-4628-8677-8a50d4f1706d"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("e9f2a713-9158-4ff8-a288-6e4e21186a77"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("c0322a73-3065-46d5-b217-e63a9a20af9a"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("bab3988c-289d-4006-9e74-b68ec9387044"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("51846af8-5860-49c3-9916-5f36d614be7c"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("ae599fd7-8e1c-4b9d-a2f7-9274f3e094f3"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("b21aee57-34c0-4e38-80aa-1477f087d237"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("a1df52d6-de4e-4e69-a420-a1dcbecfd5a6"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("7e7da1ba-e6da-4def-bcc9-22c495365517"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("99965c05-f89d-4e1c-8fff-8afeeeb34527"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("b2f4a285-16c2-42b6-8a95-fcaa81f96761"),
                            Name = "St Kitts & Nevis"
                        },
                        new
                        {
                            Id = new Guid("a4c76e13-a556-4568-a0e6-bd036b0242d2"),
                            Name = "St Lucia"
                        },
                        new
                        {
                            Id = new Guid("9bc2b122-f7c0-4891-a472-72b4ed3e6019"),
                            Name = "St Vincent"
                        },
                        new
                        {
                            Id = new Guid("d6940450-8e38-4f6f-8964-958366ac088c"),
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Id = new Guid("ae70f11d-2138-4872-b270-e357693678cb"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("df71d93a-37aa-41d4-a27e-1e9c2d991b66"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("48cc7fb9-9015-4aff-b77a-6f47101084fa"),
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("4137f969-a84c-41cb-b7d4-85e61ad2a53a"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("f538b6fe-d1bd-4b31-b080-ea402f00019d"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("8a3d97ab-0e76-4d91-8e84-95d80b4b2b38"),
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("cf3a18e8-403f-488a-b1af-32bccac0f172"),
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("25d29ddc-550f-4f63-a27a-dbd849a877c2"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("3bb76ae6-46f1-4ef8-a50e-c94e126045b4"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("8fe449ce-d4d4-4ae1-ac12-b7ab4927e3c2"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("30b3832d-e365-4a46-8cdc-965d323bd3ac"),
                            Name = "Timor L'Este"
                        },
                        new
                        {
                            Id = new Guid("e0258a4c-3933-472c-80c0-5900a5a1f428"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("18566d8c-1b6b-4df3-a84d-ae8de821e903"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("9a4107ec-8ed2-4cf2-8dfe-b74fbb15bfe2"),
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = new Guid("4957d1f6-2977-463f-9ef4-2f3a4c437903"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("4dc74f7b-72b7-4bae-8009-50ffe66d9308"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("283c609b-5dc1-4302-9468-d13989d7c863"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("4693464d-a145-4b98-a21b-4789fd4f5f05"),
                            Name = "Turks & Caicos"
                        },
                        new
                        {
                            Id = new Guid("0b5e04fa-6be6-4c9b-adc8-2d8cd7c88e4c"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("877da1b4-1d11-4495-a084-09d8223eb974"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("5d172825-1a0d-49ed-b195-4c267cd575cd"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("0b2b9871-7545-4dcb-b2cf-5e699fa1ce45"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("04708e40-6688-48ae-9e0d-c10de3551978"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("84ef6d08-4826-4cd0-84cf-2a936bfea6fb"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("9c977425-a52f-4858-a5b0-a2a922228e6e"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("ac879f0d-72c2-48b5-ae0c-30032fce552f"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("7a14cb50-52c6-4545-a776-3b85a4a1e64b"),
                            Name = "Virgin Islands (US)"
                        },
                        new
                        {
                            Id = new Guid("a8ff91de-68e9-4797-8d92-8496ee0ab150"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("2bc5dd96-1a2c-41b8-9172-b94c5c4a5b6a"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("2c2f3164-3bda-4e78-8cf4-b8b13e363d6a"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Lucky.WebAPI.Data.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = new Guid("029934fc-dd7c-49f9-8b1d-f5a834096166"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("041c4fb6-4bb0-416e-9f36-f26abf003283"),
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("b692c500-7bf9-468e-b985-e9aa1162e147"),
                            Name = "Mandarin Chinese"
                        },
                        new
                        {
                            Id = new Guid("db26e510-b24a-4138-bd7b-de27b5a36bbc"),
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = new Guid("d75cddbd-2dae-4742-9d39-655319a2ded1"),
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("adbcbc4d-7066-40f1-b44a-3d91d40952da"),
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = new Guid("bf6c2cd7-0191-4599-80ae-cb15b09328bc"),
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("7c1479ee-113f-4b8d-aaf6-4bbcd66ababc"),
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("4452e20e-f502-4710-9df9-6d24767b5d52"),
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("359063f6-86f0-430e-8a08-738874fa66a8"),
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("c3e024d4-b6fa-45f4-8789-d9ecd13b6206"),
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("ded7352a-4646-4d01-8ac6-3aa74e7dc841"),
                            Name = "Italian"
                        },
                        new
                        {
                            Id = new Guid("aff4a3ee-178b-4bc9-90e0-0570256fdf88"),
                            Name = "Korean"
                        },
                        new
                        {
                            Id = new Guid("996742c0-c2fc-476d-ad4e-dd7fd5944a6c"),
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = new Guid("00a4f20a-0ebb-4ac2-8e4f-edcf262a62fa"),
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = new Guid("9518d83e-564d-47a5-88b1-e4c14fd82e4e"),
                            Name = "Polish"
                        },
                        new
                        {
                            Id = new Guid("2d6c6103-d094-4253-b729-527ba85c6cd9"),
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = new Guid("355d13ea-d1d7-463b-a140-dc09d54a2ee7"),
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = new Guid("0eeb2025-dcb3-4edc-a0db-0cc93d0ad57a"),
                            Name = "Greek"
                        },
                        new
                        {
                            Id = new Guid("950dc732-c068-42f2-aea3-f79537731722"),
                            Name = "Danish"
                        },
                        new
                        {
                            Id = new Guid("1b81710d-3c7b-4d59-9d98-f5778bf8a9a6"),
                            Name = "Norwegian"
                        },
                        new
                        {
                            Id = new Guid("58b8d9f9-d89b-43a8-92e9-a5239b35f1db"),
                            Name = "Finnish"
                        },
                        new
                        {
                            Id = new Guid("06736f08-c525-401c-8cbe-e9e378bae33d"),
                            Name = "Czech"
                        },
                        new
                        {
                            Id = new Guid("13ce3a3d-117c-4690-b01c-31d1669cc996"),
                            Name = "Thai"
                        },
                        new
                        {
                            Id = new Guid("7d2279d2-e08b-4897-bd3e-065b9cbd1cff"),
                            Name = "Hebrew"
                        },
                        new
                        {
                            Id = new Guid("593897cf-1035-4bd4-bead-3f4663a6483e"),
                            Name = "Romanian"
                        },
                        new
                        {
                            Id = new Guid("f654db8b-bb93-4246-8442-ce0403b14150"),
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = new Guid("9b181306-9787-491d-b18a-874f6e66265d"),
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = new Guid("5815b1a8-34d8-4fd4-a8e3-247e6bbab7b6"),
                            Name = "Malay"
                        },
                        new
                        {
                            Id = new Guid("8aba5b7d-5eaa-4754-a1a5-a2e15dabef68"),
                            Name = "Slovak"
                        },
                        new
                        {
                            Id = new Guid("72112e38-5e86-4ff1-ba1f-7fb5f9b538b2"),
                            Name = "Bulgarian"
                        },
                        new
                        {
                            Id = new Guid("1d7c1c68-6e5d-4656-8e08-3476915fa70b"),
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Id = new Guid("fed59a5b-d89a-47f6-a548-fe6ab3b458d4"),
                            Name = "Slovenian"
                        },
                        new
                        {
                            Id = new Guid("02242212-3f46-4d8f-817f-b1f6b13b5bac"),
                            Name = "Latvian"
                        },
                        new
                        {
                            Id = new Guid("5679c526-7027-426d-bf5d-501a8b94a632"),
                            Name = "Croatian"
                        },
                        new
                        {
                            Id = new Guid("0e3cf1b4-0623-4cf0-ac4c-7199d8fbdfe1"),
                            Name = "Estonian"
                        },
                        new
                        {
                            Id = new Guid("5e45a71d-e664-44eb-acad-a657fe24ffc2"),
                            Name = "Serbian"
                        },
                        new
                        {
                            Id = new Guid("d28d102d-3963-4cf4-a662-16b230b5c16a"),
                            Name = "Albanian"
                        },
                        new
                        {
                            Id = new Guid("bffb65fd-4f25-404d-a4d4-3d306e6e325b"),
                            Name = "Macedonian"
                        },
                        new
                        {
                            Id = new Guid("ef69d3d8-5bf6-497e-b90d-1d64a56de2e6"),
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = new Guid("eec34bf2-d930-40e5-bb5d-a7bf048be628"),
                            Name = "Georgian"
                        },
                        new
                        {
                            Id = new Guid("88238fa4-8230-410c-b3c8-e14753673fe5"),
                            Name = "Armenian"
                        },
                        new
                        {
                            Id = new Guid("adfa9bb6-acdd-428e-8b2a-c3076ae9e329"),
                            Name = "Persian"
                        },
                        new
                        {
                            Id = new Guid("0418cae3-df38-4940-951c-dcdc1974066e"),
                            Name = "Swahili"
                        },
                        new
                        {
                            Id = new Guid("cc21a76e-8ca4-4b40-a505-e62ace411fd5"),
                            Name = "Tagalog"
                        },
                        new
                        {
                            Id = new Guid("413f502e-2cb4-438f-a7f6-2c14e49e2c58"),
                            Name = "Hausa"
                        },
                        new
                        {
                            Id = new Guid("bd52e85b-0a59-48d4-976b-531b22ccb200"),
                            Name = "Bengali"
                        },
                        new
                        {
                            Id = new Guid("698ecc54-c958-4b7a-b221-4fddf1ed2577"),
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = new Guid("a95e9be1-9c49-46ef-a911-f1734e41b7f1"),
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = new Guid("88ba79c0-bf7b-4756-8a3b-9fd29281227e"),
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = new Guid("59b217ec-077b-4d4d-92c8-48c13bca0f9e"),
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = new Guid("5c6eccbf-5e93-4327-8a60-de2ceb98a9be"),
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = new Guid("cc35b106-7785-44a8-9259-f768a8fcf681"),
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = new Guid("ca1d6fc2-4140-42d8-b45b-351f42104255"),
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = new Guid("e851ba9d-44df-48b2-be5b-2091d9671c82"),
                            Name = "Urdu"
                        });
                });

            modelBuilder.Entity("Lucky.WebAPI.Data.Models.LuckyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1acbcb48-0712-4831-bd40-0d7b740c87cc",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "ce1e3984-7296-4e3d-8e31-a23ce7830be2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Lucky.WebAPI.Data.Models.LuckyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Lucky.WebAPI.Data.Models.LuckyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky.WebAPI.Data.Models.LuckyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Lucky.WebAPI.Data.Models.LuckyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
